<a href="https://colab.research.google.com/github/OscarPasasin/etl-data-pipeline-1704862022/blob/main/notebooks/Inventario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/OscarPasasin/etl-data-pipeline-1704862022/refs/heads/main/data/raw/E_inventario.csv

In [34]:
import pandas as pd

In [35]:
url = "https://raw.githubusercontent.com/OscarPasasin/etl-data-pipeline-1704862022/refs/heads/main/data/raw/E_inventario.csv"

df = pd.read_csv(url)

df.head()

  id_inventario id_bodega            item cantidad costo_unitario
0       INV5000    BOD103     Producto 45      359         192.81
1       INV5001    BOD111      Producto 2      419         153.48
2       INV5002    BOD999   Producto 120        58         104.91
3       INV5003    BOD100     Producto 42      422       $ 138.66
4       INV5004    BOD112     Producto 79      257            NaN

In [36]:
#Exploracion de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_inventario   166 non-null    object
 1   id_bodega       161 non-null    object
 2   item            166 non-null    object
 3   cantidad        161 non-null    object
 4   costo_unitario  161 non-null    object
dtypes: object(5)
memory usage: 6.6+ KB

id_inventario     0
id_bodega         5
item              0
cantidad          5
costo_unitario    5
dtype: int64

In [37]:
#Limpieza de datos
#dejar solo numeros decimales quitar texto
E_inventario = df.copy()

E_inventario['cantidad']  = E_inventario['cantidad'].str.replace(r'\D', '', regex=True)
E_inventario['cantidad']  = E_inventario['cantidad'].str.replace('unidades','')
E_inventario['cantidad']  = E_inventario['cantidad'].str.replace('sin dato','')
E_inventario['cantidad'] = pd.to_numeric(E_inventario['cantidad'], errors='coerce')
print(E_inventario['cantidad'].value_counts(dropna=False))

cantidad
NaN      7
474.0    4
113.0    3
14.0     3
81.0     3
        ..
89.0     1
211.0    1
325.0    1
398.0    1
184.0    1
Name: count, Length: 122, dtype: int64

In [38]:
#Quitando espacios, signos dolar y texto USD a costo_unitario
E_inventario = df.copy()
E_inventario['costo_unitario'] = E_inventario['costo_unitario'].str.replace('$', '')
E_inventario['costo_unitario'] = E_inventario['costo_unitario'].str.replace(',', '')
E_inventario['costo_unitario'] = E_inventario['costo_unitario'].str.strip().str.replace('USD', '')
E_inventario['costo_unitario'] = pd.to_numeric(E_inventario['costo_unitario'], errors='coerce')
print(E_inventario['costo_unitario'].value_counts(dropna=False))

costo_unitario
NaN       5
138.66    2
333.93    2
288.22    2
139.35    2
         ..
21.57     1
135.96    1
257.03    1
48.84     1
199.13    1
Name: count, Length: 156, dtype: int64

In [39]:
#Separar válidos y rechazados

validos = E_inventario[
    E_inventario['id_inventario'].notna() &
    E_inventario['id_bodega'].notna() &
    E_inventario['item'].notna() &
    E_inventario['cantidad'].notna() &
    E_inventario['costo_unitario'].notna()
].copy()
rechazados = E_inventario[
    E_inventario['id_inventario'].isna() |
    E_inventario['id_bodega'].isna() |
    E_inventario['item'].isna() |
    E_inventario['cantidad'].isna() |
    E_inventario['costo_unitario'].isna()
].copy()

In [40]:
#Motivo de rechazo

def motivo(row):

    motivos = []

    if pd.isna(row['id_bodega']):
        motivos.append("id_bodega_vacio")
    if pd.isna(row['cantidad']):
        motivos.append("cantidad_vacio")
    if pd.isna(row['costo_unitario']):
        motivos.append("costo_unitario_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [41]:

validos.to_csv("E_inventario_curated.csv", index=False)

rechazados.to_csv("E_inventario_rejects.csv", index=False)

In [47]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:Mg85y5ihbsfGYCeJN4InkDwmJe84QY6F@dpg-d6vijdvkijhs73cshc90-a.oregon-postgres.render.com/etl_data_pipeline_1704862022"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [48]:
try:
    validos.to_sql('E_inventario_curated', engine, if_exists='replace', index=False)
    print("Table 'E_inventario_curated' created and data inserted successfully.")
except Exception as e:
    print(f"Error creating or inserting data into 'E_inventario_curated': {e}")

Table 'E_inventario_curated' created and data inserted successfully.

In [49]:
try:
    rechazados.to_sql('E_inventario_rejects', engine, if_exists='replace', index=False)
    print("Table 'E_inventario_rejects' created and data inserted successfully.")
except Exception as e:
    print(f"Error creating or inserting data into 'E_inventario_rejects': {e}")

Table 'E_inventario_rejects' created and data inserted successfully.

In [50]:
try:
    df_check = pd.read_sql("SELECT * FROM E_inventario_curated LIMIT 5", engine)
    print("\nFirst 5 rows of 'E_inventario_curated':")
    display(df_check)
except Exception as e:
    print(f"Error querying 'E_inventario_curated': {e}")

Error querying 'E_inventario_curated': (psycopg2.errors.UndefinedTable) relation "e_inventario_curated" does not exist
LINE 1: SELECT * FROM E_inventario_curated LIMIT 5
                      ^

[SQL: SELECT * FROM E_inventario_curated LIMIT 5]
(Background on this error at: https://sqlalche.me/e/20/f405)